/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as workspacesWorkspacesRouteImport } from './routes/(workspaces)/workspaces'
import { Route as workspacesWorkspaceRequestsRouteImport } from './routes/(workspaces)/workspace-requests'
import { Route as workspacesRequestWorkspaceRouteImport } from './routes/(workspaces)/request-workspace'
import { Route as workspacesAddNewWorkspaceRouteImport } from './routes/(workspaces)/add-new-workspace'
import { Route as usersUsersRouteImport } from './routes/(users)/users'
import { Route as usersAddNewUserRouteImport } from './routes/(users)/add-new-user'
import { Route as pluginsPreconfiguredPluginsRouteImport } from './routes/(plugins)/preconfigured-plugins'
import { Route as pluginsPluginTemplatesRouteImport } from './routes/(plugins)/plugin-templates'
import { Route as pluginsAddNewPluginRouteImport } from './routes/(plugins)/add-new-plugin'
import { Route as jobsJobsRouteImport } from './routes/(jobs)/jobs'
import { Route as jobsAddNewJobRouteImport } from './routes/(jobs)/add-new-job'
import { Route as agentsAgentsRouteImport } from './routes/(agents)/agents'
import { Route as agentsAddNewAgentRouteImport } from './routes/(agents)/add-new-agent'
import { Route as jobsJobsJobIdRouteImport } from './routes/(jobs)/jobs_.$jobId'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const workspacesWorkspacesRoute = workspacesWorkspacesRouteImport.update({
  id: '/(workspaces)/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const workspacesWorkspaceRequestsRoute =
  workspacesWorkspaceRequestsRouteImport.update({
    id: '/(workspaces)/workspace-requests',
    path: '/workspace-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const workspacesRequestWorkspaceRoute =
  workspacesRequestWorkspaceRouteImport.update({
    id: '/(workspaces)/request-workspace',
    path: '/request-workspace',
    getParentRoute: () => rootRouteImport,
  } as any)
const workspacesAddNewWorkspaceRoute =
  workspacesAddNewWorkspaceRouteImport.update({
    id: '/(workspaces)/add-new-workspace',
    path: '/add-new-workspace',
    getParentRoute: () => rootRouteImport,
  } as any)
const usersUsersRoute = usersUsersRouteImport.update({
  id: '/(users)/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const usersAddNewUserRoute = usersAddNewUserRouteImport.update({
  id: '/(users)/add-new-user',
  path: '/add-new-user',
  getParentRoute: () => rootRouteImport,
} as any)
const pluginsPreconfiguredPluginsRoute =
  pluginsPreconfiguredPluginsRouteImport.update({
    id: '/(plugins)/preconfigured-plugins',
    path: '/preconfigured-plugins',
    getParentRoute: () => rootRouteImport,
  } as any)
const pluginsPluginTemplatesRoute = pluginsPluginTemplatesRouteImport.update({
  id: '/(plugins)/plugin-templates',
  path: '/plugin-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const pluginsAddNewPluginRoute = pluginsAddNewPluginRouteImport.update({
  id: '/(plugins)/add-new-plugin',
  path: '/add-new-plugin',
  getParentRoute: () => rootRouteImport,
} as any)
const jobsJobsRoute = jobsJobsRouteImport.update({
  id: '/(jobs)/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const jobsAddNewJobRoute = jobsAddNewJobRouteImport.update({
  id: '/(jobs)/add-new-job',
  path: '/add-new-job',
  getParentRoute: () => rootRouteImport,
} as any)
const agentsAgentsRoute = agentsAgentsRouteImport.update({
  id: '/(agents)/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const agentsAddNewAgentRoute = agentsAddNewAgentRouteImport.update({
  id: '/(agents)/add-new-agent',
  path: '/add-new-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const jobsJobsJobIdRoute = jobsJobsJobIdRouteImport.update({
  id: '/(jobs)/jobs_/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/add-new-agent': typeof agentsAddNewAgentRoute
  '/agents': typeof agentsAgentsRoute
  '/add-new-job': typeof jobsAddNewJobRoute
  '/jobs': typeof jobsJobsRoute
  '/add-new-plugin': typeof pluginsAddNewPluginRoute
  '/plugin-templates': typeof pluginsPluginTemplatesRoute
  '/preconfigured-plugins': typeof pluginsPreconfiguredPluginsRoute
  '/add-new-user': typeof usersAddNewUserRoute
  '/users': typeof usersUsersRoute
  '/add-new-workspace': typeof workspacesAddNewWorkspaceRoute
  '/request-workspace': typeof workspacesRequestWorkspaceRoute
  '/workspace-requests': typeof workspacesWorkspaceRequestsRoute
  '/workspaces': typeof workspacesWorkspacesRoute
  '/jobs/$jobId': typeof jobsJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/add-new-agent': typeof agentsAddNewAgentRoute
  '/agents': typeof agentsAgentsRoute
  '/add-new-job': typeof jobsAddNewJobRoute
  '/jobs': typeof jobsJobsRoute
  '/add-new-plugin': typeof pluginsAddNewPluginRoute
  '/plugin-templates': typeof pluginsPluginTemplatesRoute
  '/preconfigured-plugins': typeof pluginsPreconfiguredPluginsRoute
  '/add-new-user': typeof usersAddNewUserRoute
  '/users': typeof usersUsersRoute
  '/add-new-workspace': typeof workspacesAddNewWorkspaceRoute
  '/request-workspace': typeof workspacesRequestWorkspaceRoute
  '/workspace-requests': typeof workspacesWorkspaceRequestsRoute
  '/workspaces': typeof workspacesWorkspacesRoute
  '/jobs/$jobId': typeof jobsJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/(agents)/add-new-agent': typeof agentsAddNewAgentRoute
  '/(agents)/agents': typeof agentsAgentsRoute
  '/(jobs)/add-new-job': typeof jobsAddNewJobRoute
  '/(jobs)/jobs': typeof jobsJobsRoute
  '/(plugins)/add-new-plugin': typeof pluginsAddNewPluginRoute
  '/(plugins)/plugin-templates': typeof pluginsPluginTemplatesRoute
  '/(plugins)/preconfigured-plugins': typeof pluginsPreconfiguredPluginsRoute
  '/(users)/add-new-user': typeof usersAddNewUserRoute
  '/(users)/users': typeof usersUsersRoute
  '/(workspaces)/add-new-workspace': typeof workspacesAddNewWorkspaceRoute
  '/(workspaces)/request-workspace': typeof workspacesRequestWorkspaceRoute
  '/(workspaces)/workspace-requests': typeof workspacesWorkspaceRequestsRoute
  '/(workspaces)/workspaces': typeof workspacesWorkspacesRoute
  '/(jobs)/jobs_/$jobId': typeof jobsJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/add-new-agent'
    | '/agents'
    | '/add-new-job'
    | '/jobs'
    | '/add-new-plugin'
    | '/plugin-templates'
    | '/preconfigured-plugins'
    | '/add-new-user'
    | '/users'
    | '/add-new-workspace'
    | '/request-workspace'
    | '/workspace-requests'
    | '/workspaces'
    | '/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/add-new-agent'
    | '/agents'
    | '/add-new-job'
    | '/jobs'
    | '/add-new-plugin'
    | '/plugin-templates'
    | '/preconfigured-plugins'
    | '/add-new-user'
    | '/users'
    | '/add-new-workspace'
    | '/request-workspace'
    | '/workspace-requests'
    | '/workspaces'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/(agents)/add-new-agent'
    | '/(agents)/agents'
    | '/(jobs)/add-new-job'
    | '/(jobs)/jobs'
    | '/(plugins)/add-new-plugin'
    | '/(plugins)/plugin-templates'
    | '/(plugins)/preconfigured-plugins'
    | '/(users)/add-new-user'
    | '/(users)/users'
    | '/(workspaces)/add-new-workspace'
    | '/(workspaces)/request-workspace'
    | '/(workspaces)/workspace-requests'
    | '/(workspaces)/workspaces'
    | '/(jobs)/jobs_/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  agentsAddNewAgentRoute: typeof agentsAddNewAgentRoute
  agentsAgentsRoute: typeof agentsAgentsRoute
  jobsAddNewJobRoute: typeof jobsAddNewJobRoute
  jobsJobsRoute: typeof jobsJobsRoute
  pluginsAddNewPluginRoute: typeof pluginsAddNewPluginRoute
  pluginsPluginTemplatesRoute: typeof pluginsPluginTemplatesRoute
  pluginsPreconfiguredPluginsRoute: typeof pluginsPreconfiguredPluginsRoute
  usersAddNewUserRoute: typeof usersAddNewUserRoute
  usersUsersRoute: typeof usersUsersRoute
  workspacesAddNewWorkspaceRoute: typeof workspacesAddNewWorkspaceRoute
  workspacesRequestWorkspaceRoute: typeof workspacesRequestWorkspaceRoute
  workspacesWorkspaceRequestsRoute: typeof workspacesWorkspaceRequestsRoute
  workspacesWorkspacesRoute: typeof workspacesWorkspacesRoute
  jobsJobsJobIdRoute: typeof jobsJobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(workspaces)/workspaces': {
      id: '/(workspaces)/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof workspacesWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(workspaces)/workspace-requests': {
      id: '/(workspaces)/workspace-requests'
      path: '/workspace-requests'
      fullPath: '/workspace-requests'
      preLoaderRoute: typeof workspacesWorkspaceRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(workspaces)/request-workspace': {
      id: '/(workspaces)/request-workspace'
      path: '/request-workspace'
      fullPath: '/request-workspace'
      preLoaderRoute: typeof workspacesRequestWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(workspaces)/add-new-workspace': {
      id: '/(workspaces)/add-new-workspace'
      path: '/add-new-workspace'
      fullPath: '/add-new-workspace'
      preLoaderRoute: typeof workspacesAddNewWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(users)/users': {
      id: '/(users)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof usersUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(users)/add-new-user': {
      id: '/(users)/add-new-user'
      path: '/add-new-user'
      fullPath: '/add-new-user'
      preLoaderRoute: typeof usersAddNewUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(plugins)/preconfigured-plugins': {
      id: '/(plugins)/preconfigured-plugins'
      path: '/preconfigured-plugins'
      fullPath: '/preconfigured-plugins'
      preLoaderRoute: typeof pluginsPreconfiguredPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(plugins)/plugin-templates': {
      id: '/(plugins)/plugin-templates'
      path: '/plugin-templates'
      fullPath: '/plugin-templates'
      preLoaderRoute: typeof pluginsPluginTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(plugins)/add-new-plugin': {
      id: '/(plugins)/add-new-plugin'
      path: '/add-new-plugin'
      fullPath: '/add-new-plugin'
      preLoaderRoute: typeof pluginsAddNewPluginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(jobs)/jobs': {
      id: '/(jobs)/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof jobsJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(jobs)/add-new-job': {
      id: '/(jobs)/add-new-job'
      path: '/add-new-job'
      fullPath: '/add-new-job'
      preLoaderRoute: typeof jobsAddNewJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(agents)/agents': {
      id: '/(agents)/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof agentsAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(agents)/add-new-agent': {
      id: '/(agents)/add-new-agent'
      path: '/add-new-agent'
      fullPath: '/add-new-agent'
      preLoaderRoute: typeof agentsAddNewAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(jobs)/jobs_/$jobId': {
      id: '/(jobs)/jobs_/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof jobsJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  agentsAddNewAgentRoute: agentsAddNewAgentRoute,
  agentsAgentsRoute: agentsAgentsRoute,
  jobsAddNewJobRoute: jobsAddNewJobRoute,
  jobsJobsRoute: jobsJobsRoute,
  pluginsAddNewPluginRoute: pluginsAddNewPluginRoute,
  pluginsPluginTemplatesRoute: pluginsPluginTemplatesRoute,
  pluginsPreconfiguredPluginsRoute: pluginsPreconfiguredPluginsRoute,
  usersAddNewUserRoute: usersAddNewUserRoute,
  usersUsersRoute: usersUsersRoute,
  workspacesAddNewWorkspaceRoute: workspacesAddNewWorkspaceRoute,
  workspacesRequestWorkspaceRoute: workspacesRequestWorkspaceRoute,
  workspacesWorkspaceRequestsRoute: workspacesWorkspaceRequestsRoute,
  workspacesWorkspacesRoute: workspacesWorkspacesRoute,
  jobsJobsJobIdRoute: jobsJobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
